namespace: extreme
name: exos
version: 0.1.1
readme: README.md
authors:
    - Ujwal Komarla
description: An Ansible collection for managing Extreme Networks devices running EXOS.
license: GPL-3.0-or-later
license_file: COPYING
dependencies:
  "ansible.netcommon": "*"
repository: git@github.com:extremenetworks/ansible_collections.extreme.exos.git
documentation: https://github.com/extremenetworks/ansible_collections.extreme.exos/tree/master/docs
homepage: https://github.com/extremenetworks/ansible_collections.extreme.exos
issues: https://github.com/extremenetworks/ansible_collections.extreme.exos/issues
tags:
    - networking
    - exos
    - extreme
    - switching
    - collection
